# Generated by Django 5.2.7 on 2025-10-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0002_subject_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
    ]
