# Generated by Django 5.2.7 on 2025-10-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0003_quiz_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Question'),
        ),
    ]
